reddit_subs = [
    # Original paranormal subs
    "paranormal",
    "HighStrangeness",
    "ghosts",
    "UFOs",
    "aliens",
    "cryptids",
    "truecreepy",
    "Glitch_in_the_Matrix",
    "nosleep",
    "LetsNotMeet",
    # Video-rich paranormal subreddits
    "ParanormalVideos",
    "GhostVideos",
    "UFOvideos",
    "CryptidSightings",
    "SecurityCameras",
    "CaughtOnCamera",
    "UnexplainedPhotos",
    "BackyardChickens",
    "TrailCam",
    "DashCam",
    # More active paranormal communities
    "Thetruthishere",
    "Humanoidencounters",
    "CrawlerSightings",
    "DogMan",
    "Bigfoot",
    "SkinWalkers",
    "Wendigo",
    "Missing411",
    # Horror and creepy video content
    "CreepyVideos",
    "DisturbingMovies",
    "UnsolvedMysteries",
    "RBI",
    "Mystery",
    # Supernatural and occult
    "Occult",
    "Witchcraft",
    "Demons",
    "Possession",
    "Exorcism",
    # Strange phenomena
    "TimeSlip",
    "DimensionalJumping",
    "MandelaEffect",
    "Retconned",
    "Telepathy",
    "Precognition",
    # Video-focused general subs
    "PublicFreakout",
    "AbruptChaos",
    "Unexpected",
    "BlackMagicFuckery",
    "Damnthatsinteresting",
    "InterestingAsFuck",
    "WTF",
    "Creepy",
    "OddlyTerrifying",
    "LiminalSpace",
    # International paranormal
    "ParanormalUK",
    "ParanormalIndia",
    "JapaneseHorror",
    "MexicanFolklore",
    # Specific creature subs
    "Mothman",
    "Chupacabra",
    "Jersey_Devil",
    "Thunderbird",
    "LakeMonsters",
    "SeaSerpents",
    # Investigation and evidence subs
    "ParanormalInvestigators",
    "GhostHunting",
    "EVP",
    "SpiritBox",
    "Ouija",
    "Seances",
    # --- Indian Subreddits ---
    "india",
    "IndiaSpeaks",
    "AskIndia",
    "Indiasocial",
    "Bangalore",
    "Mumbai",
    "Delhi",
    "Hyderabad",
    "Kolkata",
    "kerala",
    "tamilnadu",
    "maharashtra",
    "bihar",
    "uttarpradesh",
    "jeeneetards",
    "cbse",
    "upsc",
    "indianmedschool",
    "catpreparation",
    "btechtards",
    "indians_studyabroad",
    "relationshipindia",
    "askindianwomen",
    "TwoXIndia",
    "desiweddings",
    "arrangedmarriage",
    "indianfashionaddicts",
    "indianskincareaddicts",
    "indianbeautydeals",
    "ABCDesis",
    # --- Indian State-Based Subreddits ---
    "Maharashtra",
    "TamilNadu",
    "Kerala",
    "Gujarat",
    "Punjab",
    "WestBengal",
    "Rajasthan",
    "Uttarakhand",
    "Goa",
    # --- News Subreddits ---
    "news",
    "worldnews",
    "IndiaNews",
    "Indianewsroom",
    "InthenewsIndia",
    "politics",
    "nottheonion",
    "upliftingnews",
    "business",
    "technology",
    "science",
    "Futurology",
    "CoronavirusIndia",
    "TheOnion",
    # --- Hinduism / Indian Spirituality Subreddits ---
    "hinduism",
    "SanatanDharma",
    "vedanta",
    "BhagavadGita",
    "narasimha",
    "IndianSpirituality",
    "Shaivism",
    "Vaishnavism",
    "HinduCulture",
    "Upanishads",
    # --- Indian News Subreddits ---
    "IndiaInNews",  # curated Indian news
    "IndianMedia",  # discussion about Indian media
    "IndiaPolitics",  # politics and policy news
    "IndianCurrentAffairs",  # current affairs from India
    "IndianEconomy",  # finance & economy related news
    "IndiaTech",  # technology news from India
    "IndiaBusiness",  # business news from India
    "IndiaUpdates",  # latest updates/news from India
]

reddit_subs.reverse()
